export default {
  ISARRAY: require('./ISARRAY'),
  ISEMAIL: require('./ISEMAIL'),
  ISERR: require('./ISERR'),
  ISEVEN: require('./ISEVEN'),
  ISNA: require('./ISNA'),
  ISNUMBER: require('./ISNUMBER'),
  ISODD: require('./ISODD'),
  ISTEXT: require('./ISTEXT'),
  ISRANGE: require('./ISRANGE'),
  ISREF: require('./ISREF'),
  N: require('./N'),
  NA: require('./NA'),
  PRECEDENTS: require('./PRECEDENTS'),
  SHEETS: require('./SHEETS'),
  TYPE: require('./TYPE'),
}
